### ISSUE TITLE
Error with hook to extend routes

### ISSUE THREAD

**Issue by manuGil** [CUSP-Urban-Science-and-Policy/Citizen-Voice#169]
After upgrading to NuxtJS 3.14, this hook raised an error. We must check if and how the `nuxt.config.js` must be modified.

Code that causes the error:
```javascript
  hooks: {
      'pages:extend'(routes) {
           routes.push({
               name: "survey-design",
               path: "/design/surveys/create",
               file: path.resolve(__dirname, './pages/design/surveys/[_id]/index.vue')
           });
           return routes
       }
  },
```

Error:

```bash
 ERROR  [GET] "http://django-app:8000/api/v2/surveys": <no response> fetch failed

  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  at async AsyncFunction.$fetchRaw2 [as raw] (node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:270:14)
  at async Object.handler (node_modules/nuxt-api-party/dist/runtime/server/handler.js:47:22)
  at async node_modules/h3/dist/index.mjs:1978:19
  at async Object.callAsync (node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (node_modules/h3/dist/index.mjs:2270:7)
```

**Comment by manuGil** [comment]
This issue went away after updating the configuration
